development:
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  encoding: unicode
  database: fun_with_twitter_dev
  username: fwt
  password: fwt

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  database: fun_with_twitter_test
  username: fwt
  password: fwt

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode